<?php

namespace Database\Seeders;

use App\Enums\BillingType;
use App\Enums\PricingType;
use App\Enums\ServiceType;
use App\Models\Currency;
use App\Models\Service;
use App\Models\ServiceCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $currencyId = Currency::query()->where('code', 'USD')->value('id');

        $services = [
            [
                'code' => 'DEV-SOFT',
                'category' => 'SOFTWARE_DEV',
                'name' => 'Software Development',
                'name_ar' => 'تطوير البرمجيات',
                'slug' => 'software-development',
                'short_description' => 'Design and build scalable custom software tailored to your business processes.',
                'short_description_ar' => 'تصميم وبناء برمجيات مخصصة قابلة للتوسع تناسب عمليات أعمالك.',
                'description' => 'End-to-end custom software development for enterprise and growing organizations.',
                'description_ar' => 'تطوير برمجيات مخصصة من البداية للنهاية للمؤسسات والشركات النامية.',
                'overview' => 'We help businesses define requirements, design architecture, and deliver secure maintainable software products.',
                'overview_ar' => 'نساعد الشركات على تحديد المتطلبات وتصميم البنية وتسليم منتجات برمجية آمنة وقابلة للصيانة.',
                'service_type' => ServiceType::Development,
                'billing_type' => BillingType::TimeAndMaterial,
                'pricing_type' => PricingType::QuoteRequired,
                'default_price' => 450,
                'is_featured' => false,
                'is_project_service' => true,
                'sort_order' => 10,
            ],
            [
                'code' => 'DEV-MOB',
                'category' => 'MOBILE_APPS',
                'name' => 'Mobile Application Development',
                'name_ar' => 'تطوير تطبيقات الجوال',
                'slug' => 'mobile-application-development',
                'short_description' => 'Build modern, scalable mobile applications for iOS and Android.',
                'short_description_ar' => 'تطوير تطبيقات جوال حديثة وقابلة للتوسع لأنظمة iOS وAndroid.',
                'description' => 'Cross-platform and native mobile application development with secure APIs and polished UX.',
                'description_ar' => 'تطوير تطبيقات جوال متعددة المنصات وأصلية مع واجهات برمجة آمنة وتجربة مستخدم احترافية.',
                'overview' => 'From discovery and UI/UX to store deployment and ongoing maintenance, we deliver production-ready mobile apps.',
                'overview_ar' => 'من الاستكشاف وتصميم الواجهات إلى النشر في المتاجر والدعم المستمر، نقدم تطبيقات جوال جاهزة للإنتاج.',
                'service_type' => ServiceType::Development,
                'billing_type' => BillingType::Fixed,
                'pricing_type' => PricingType::StartingFrom,
                'starting_price' => 25000,
                'default_price' => 75000,
                'is_featured' => false,
                'is_project_service' => true,
                'sort_order' => 11,
            ],
            [
                'code' => 'DEV-WEB',
                'category' => 'WEB_APPS',
                'name' => 'Web Application Development',
                'name_ar' => 'تطوير تطبيقات الويب',
                'slug' => 'web-application-development',
                'short_description' => 'Modern web applications, portals, and business platforms.',
                'short_description_ar' => 'تطبيقات ويب وبوابات ومنصات أعمال حديثة.',
                'description' => 'Secure, responsive web applications built with modern frameworks and clean architecture.',
                'description_ar' => 'تطبيقات ويب آمنة ومتجاوبة مبنية بأطر عمل حديثة وهندسة نظيفة.',
                'overview' => 'We design and implement web platforms that support growth, integrations, and operational excellence.',
                'overview_ar' => 'نصمم وننفذ منصات ويب تدعم النمو والتكامل والتميز التشغيلي.',
                'service_type' => ServiceType::Development,
                'billing_type' => BillingType::TimeAndMaterial,
                'pricing_type' => PricingType::QuoteRequired,
                'default_price' => 450,
                'is_featured' => false,
                'is_project_service' => true,
                'sort_order' => 12,
            ],
            [
                'code' => 'CLD-SOL',
                'category' => 'CLOUD',
                'name' => 'Cloud Solutions',
                'name_ar' => 'الحلول السحابية',
                'slug' => 'cloud-solutions',
                'short_description' => 'Cloud architecture, migration, and managed cloud operations.',
                'short_description_ar' => 'هندسة سحابية وترحيل وتشغيل سحابي مدار.',
                'description' => 'Design and operate reliable cloud environments on AWS and Azure.',
                'description_ar' => 'تصميم وتشغيل بيئات سحابية موثوقة على AWS وAzure.',
                'overview' => 'We help organizations adopt cloud with secure architecture, cost control, and operational readiness.',
                'overview_ar' => 'نساعد المؤسسات على تبني السحابة بهندسة آمنة وتحكم في التكاليف واستعداد تشغيلي.',
                'service_type' => ServiceType::Cloud,
                'billing_type' => BillingType::Milestone,
                'pricing_type' => PricingType::Custom,
                'default_price' => 25000,
                'is_featured' => false,
                'is_project_service' => true,
                'sort_order' => 13,
            ],
            [
                'code' => 'OPS-CICD',
                'category' => 'DEVOPS',
                'name' => 'DevOps & CI/CD',
                'name_ar' => 'DevOps والتكامل المستمر',
                'slug' => 'devops-cicd',
                'short_description' => 'Automation, CI/CD pipelines, and platform reliability.',
                'short_description_ar' => 'الأتمتة وخطوط التكامل المستمر وموثوقية المنصات.',
                'description' => 'Build delivery pipelines, containers, and observability for faster safer releases.',
                'description_ar' => 'بناء خطوط التسليم والحاويات والمراقبة لإصدارات أسرع وأكثر أمانًا.',
                'overview' => 'Our DevOps practice improves delivery speed while strengthening security and reliability.',
                'overview_ar' => 'تحسن ممارسات DevOps لدينا سرعة التسليم مع تعزيز الأمن والموثوقية.',
                'service_type' => ServiceType::Infrastructure,
                'billing_type' => BillingType::Fixed,
                'pricing_type' => PricingType::StartingFrom,
                'starting_price' => 12000,
                'default_price' => 12000,
                'is_featured' => false,
                'is_project_service' => true,
                'sort_order' => 14,
            ],
            [
                'code' => 'SEC-AUDIT',
                'category' => 'CYBER_SECURITY',
                'name' => 'Cyber Security Services',
                'name_ar' => 'خدمات الأمن السيبراني',
                'slug' => 'cyber-security-services',
                'short_description' => 'Security assessments, hardening, and compliance advisory.',
                'short_description_ar' => 'تقييمات أمنية وتقوية الأنظمة واستشارات الامتثال.',
                'description' => 'Protect systems and data through assessments, penetration testing, and secure design.',
                'description_ar' => 'حماية الأنظمة والبيانات عبر التقييمات واختبارات الاختراق والتصميم الآمن.',
                'overview' => 'We assess risks and implement practical security controls aligned with business priorities.',
                'overview_ar' => 'نقيّم المخاطر وننفذ ضوابط أمنية عملية متوافقة مع أولويات العمل.',
                'service_type' => ServiceType::Security,
                'billing_type' => BillingType::Fixed,
                'pricing_type' => PricingType::QuoteRequired,
                'default_price' => 20000,
                'is_featured' => false,
                'is_consulting' => true,
                'sort_order' => 15,
            ],
            [
                'code' => 'INF-CORE',
                'category' => 'INFRASTRUCTURE',
                'name' => 'IT Infrastructure',
                'name_ar' => 'البنية التحتية لتقنية المعلومات',
                'slug' => 'it-infrastructure',
                'short_description' => 'Reliable infrastructure design and implementation.',
                'short_description_ar' => 'تصميم وتنفيذ بنية تحتية موثوقة.',
                'description' => 'Servers, storage, virtualization, and hybrid infrastructure solutions.',
                'description_ar' => 'حلول الخوادم والتخزين والافتراضية والبنية التحتية الهجينة.',
                'overview' => 'We design resilient infrastructure foundations that support secure business operations.',
                'overview_ar' => 'نصمم أساسات بنية تحتية مرنة تدعم العمليات التجارية الآمنة.',
                'service_type' => ServiceType::Infrastructure,
                'billing_type' => BillingType::Milestone,
                'pricing_type' => PricingType::Custom,
                'default_price' => 40000,
                'is_project_service' => true,
                'sort_order' => 16,
            ],
            [
                'code' => 'NET-DES',
                'category' => 'NETWORKING',
                'name' => 'Networking Solutions',
                'name_ar' => 'حلول الشبكات',
                'slug' => 'networking-solutions',
                'short_description' => 'Enterprise network design and implementation.',
                'short_description_ar' => 'تصميم وتنفيذ شبكات المؤسسات.',
                'description' => 'Secure LAN/WAN, wireless, and network modernization projects.',
                'description_ar' => 'مشاريع شبكات محلية وواسعة ولاسلكية وتحديث الشبكات بأمان.',
                'overview' => 'We plan and deliver network solutions that balance performance, security, and manageability.',
                'overview_ar' => 'نخطط وننفذ حلول شبكات توازن بين الأداء والأمن وسهولة الإدارة.',
                'service_type' => ServiceType::Infrastructure,
                'billing_type' => BillingType::Milestone,
                'pricing_type' => PricingType::ContactUs,
                'default_price' => 40000,
                'is_project_service' => true,
                'sort_order' => 17,
            ],
            [
                'code' => 'DB-SOL',
                'category' => 'DATABASE',
                'name' => 'Database Solutions',
                'name_ar' => 'حلول قواعد البيانات',
                'slug' => 'database-solutions',
                'short_description' => 'Database architecture, optimization, and administration.',
                'short_description_ar' => 'هندسة وتحسين وإدارة قواعد البيانات.',
                'description' => 'Design, tune, and operate relational databases for critical workloads.',
                'description_ar' => 'تصميم وضبط وتشغيل قواعد البيانات العلائقية لأحمال العمل الحرجة.',
                'overview' => 'We deliver database solutions focused on integrity, performance, and recoverability.',
                'overview_ar' => 'نقدم حلول قواعد بيانات تركز على السلامة والأداء وقابلية الاستعادة.',
                'service_type' => ServiceType::Development,
                'billing_type' => BillingType::Hourly,
                'pricing_type' => PricingType::Custom,
                'default_price' => 400,
                'is_project_service' => true,
                'sort_order' => 18,
            ],
            [
                'code' => 'INT-SYS',
                'category' => 'INTEGRATION',
                'name' => 'System Integration',
                'name_ar' => 'تكامل الأنظمة',
                'slug' => 'system-integration',
                'short_description' => 'Connect systems, APIs, and enterprise platforms.',
                'short_description_ar' => 'ربط الأنظمة وواجهات البرمجة ومنصات المؤسسات.',
                'description' => 'Reliable integrations that reduce manual work and improve data consistency.',
                'description_ar' => 'تكاملات موثوقة تقلل العمل اليدوي وتحسن اتساق البيانات.',
                'overview' => 'We design integration patterns and implement secure API and messaging solutions.',
                'overview_ar' => 'نصمم أنماط التكامل وننفذ حلول واجهات برمجة ورسائل آمنة.',
                'service_type' => ServiceType::Development,
                'billing_type' => BillingType::Hourly,
                'pricing_type' => PricingType::QuoteRequired,
                'default_price' => 400,
                'is_project_service' => true,
                'sort_order' => 19,
            ],
            [
                'code' => 'CON-STRAT',
                'category' => 'IT_CONSULTING',
                'name' => 'IT Consulting',
                'name_ar' => 'الاستشارات التقنية',
                'slug' => 'it-consulting',
                'short_description' => 'Technology strategy and advisory for business outcomes.',
                'short_description_ar' => 'استراتيجية تقنية واستشارات تركز على نتائج الأعمال.',
                'description' => 'Independent consulting for architecture, digital transformation, and technology decisions.',
                'description_ar' => 'استشارات مستقلة للهندسة والتحول الرقمي والقرارات التقنية.',
                'overview' => 'We help leadership teams make informed technology decisions and prioritize investments.',
                'overview_ar' => 'نساعد فرق القيادة على اتخاذ قرارات تقنية مدروسة وترتيب أولويات الاستثمار.',
                'service_type' => ServiceType::Consulting,
                'billing_type' => BillingType::Hourly,
                'pricing_type' => PricingType::StartingFrom,
                'starting_price' => 500,
                'default_price' => 500,
                'is_featured' => false,
                'is_consulting' => true,
                'sort_order' => 20,
            ],
            [
                'code' => 'SUP-TECH',
                'category' => 'SUPPORT',
                'name' => 'Technical Support',
                'name_ar' => 'الدعم الفني',
                'slug' => 'technical-support',
                'short_description' => 'Responsive technical support and system maintenance.',
                'short_description_ar' => 'دعم فني سريع وصيانة للأنظمة.',
                'description' => 'Managed support services to keep applications and infrastructure healthy.',
                'description_ar' => 'خدمات دعم مدارة للحفاظ على صحة التطبيقات والبنية التحتية.',
                'overview' => 'Our support team monitors issues, resolves incidents, and maintains operational continuity.',
                'overview_ar' => 'يراقب فريق الدعم المشكلات ويعالج الحوادث ويحافظ على استمرارية التشغيل.',
                'service_type' => ServiceType::Support,
                'billing_type' => BillingType::Recurring,
                'pricing_type' => PricingType::ContactUs,
                'default_price' => 5000,
                'is_recurring' => true,
                'sort_order' => 21,
            ],
            [
                'code' => 'TRN-TECH',
                'category' => 'TRAINING',
                'name' => 'Technical Training',
                'name_ar' => 'التدريب التقني',
                'slug' => 'technical-training',
                'short_description' => 'Hands-on technical training for teams and organizations.',
                'short_description_ar' => 'تدريب تقني عملي للفرق والمؤسسات.',
                'description' => 'Custom training programs covering development, cloud, security, and operations.',
                'description_ar' => 'برامج تدريب مخصصة تغطي التطوير والسحابة والأمن والعمليات.',
                'overview' => 'We deliver practical workshops that build team capability around your technology stack.',
                'overview_ar' => 'نقدم ورش عمل عملية تبني قدرات الفريق حول حزمة التقنيات الخاصة بكم.',
                'service_type' => ServiceType::Training,
                'billing_type' => BillingType::Fixed,
                'pricing_type' => PricingType::Custom,
                'default_price' => 8000,
                'sort_order' => 22,
            ],
            [
                'code' => 'BNK-CORE',
                'category' => 'CORE_BANKING',
                'name' => 'Core Banking Solutions',
                'name_ar' => 'استشارات وهندسة النظم المصرفية والمالية',
                'slug' => 'core-banking-solutions',
                'short_description' => 'Specialized consulting for banks: core assessment, branch rollout, FX/remittance, wallets, and regulatory compliance.',
                'short_description_ar' => 'استشارات متخصصة للبنوك: تقييم النظام المركزي، إطلاق الفروع، الصرافة والحوالات، المحافظ، والامتثال الرقابي.',
                'description' => 'End-to-end consulting and engineering for core banking platforms serving banks and financial institutions: performance under load, accounting workflows, branch expansion, FX and remittance cycles, digital wallets, and audit-ready controls aligned with central bank expectations.',
                'description_ar' => 'استشارات وهندسة شاملة لمنصات النظم المصرفية المركزية للبنوك والمؤسسات المالية: الأداء تحت الضغط، مسارات القيود المحاسبية، توسعة الفروع، دورات الصرافة والحوالات والمحافظ الرقمية، وضوابط التدقيق والامتثال وفق متطلبات البنوك المركزية.',
                'overview' => 'We partner with banks and financial institutions to stabilize core systems, open new branches safely, accelerate EOD/EOM processing, and strengthen compliance, audit trails, and financial controls.',
                'overview_ar' => 'نشارك البنوك والمؤسسات المالية في استقرار الأنظمة الأساسية، وإطلاق الفروع بأمان، وتسريع الإغلاق اليومي والدوري، وتعزيز الامتثال وسجلات التدقيق والضوابط المالية.',
                'service_type' => ServiceType::Consulting,
                'billing_type' => BillingType::Milestone,
                'pricing_type' => PricingType::QuoteRequired,
                'default_price' => 100000,
                'is_featured' => true,
                'is_consulting' => true,
                'is_project_service' => true,
                'sort_order' => 1,
            ],
            [
                'code' => 'API-MGMT',
                'category' => 'API_INTEGRATION',
                'name' => 'API Management & Integration',
                'name_ar' => 'خدمات الربط والتكامل وإدارة الواجهات',
                'slug' => 'api-management-integration',
                'short_description' => 'Banking-grade REST/SOAP APIs, ATM/payment switches, card networks, and monitored integration hubs.',
                'short_description_ar' => 'واجهات مصرفية REST/SOAP، محولات صراف آلي ودفع، شبكات بطاقات، ومراكز تكامل مراقبة.',
                'description' => 'Design and operate secure high-performance financial integrations: OAuth 2.0/JWT/mTLS, ISO 8583 ATM switches, Mastercard/Visa connectivity, WebLogic/Tomcat middleware, SSL/TLS hardening, and real-time API observability for banks and payment partners.',
                'description_ar' => 'تصميم وتشغيل تكاملات مالية آمنة عالية الأداء: OAuth 2.0 وJWT وmTLS، محولات ATM ببروتوكول ISO 8583، الربط مع Mastercard/Visa، وسائط WebLogic/Tomcat، تأمين SSL/TLS، ومراقبة لحظية للواجهات للبنوك وشركاء الدفع.',
                'overview' => 'We connect banking cores to channels and partners with audited, documented, and monitored APIs that remain resilient at peak financial transaction volumes.',
                'overview_ar' => 'نربط الأنظمة المصرفية المركزية بالقنوات والشركاء عبر واجهات موثّقة ومراقبة وقابلة للتدقيق تتحمل ذروة المعاملات المالية.',
                'service_type' => ServiceType::Infrastructure,
                'billing_type' => BillingType::TimeAndMaterial,
                'pricing_type' => PricingType::QuoteRequired,
                'default_price' => 80000,
                'is_featured' => true,
                'is_project_service' => true,
                'sort_order' => 2,
            ],
            [
                'code' => 'DB-APEX',
                'category' => 'DATABASE_APEX',
                'name' => 'Enterprise Database & Oracle APEX',
                'name_ar' => 'هندسة وتحسين قواعد البيانات المؤسسية وتطبيقات APEX',
                'slug' => 'enterprise-database-apex',
                'short_description' => 'Performance tuning, Oracle APEX dashboards, automation, and disaster recovery for financial data platforms.',
                'short_description_ar' => 'ضبط الأداء ولوحات Oracle APEX والأتمتة والتعافي من الكوارث لمنصات البيانات المالية.',
                'description' => 'Enterprise database performance engineering for banking and finance workloads: SQL/PL-SQL tuning, interactive APEX dashboards, DBMS_SCHEDULER automation, tablespace monitoring, and hot/cold backup with measurable RPO/RTO.',
                'description_ar' => 'هندسة أداء قواعد البيانات لأحمال العمل المصرفية والمالية: ضبط SQL/PL-SQL، لوحات APEX التفاعلية، أتمتة DBMS_SCHEDULER، مراقبة Tablespaces، ونسخ احتياطي ساخن وبارد مع مؤشرات RPO وRTO قابلة للقياس.',
                'overview' => 'We reduce query latency on mission-critical financial databases, unlock secure internal APEX apps, and harden continuity for regulated data platforms.',
                'overview_ar' => 'نقلّص زمن الاستعلامات على قواعد البيانات المالية الحرجة، ونمكّن تطبيقات APEX داخلية آمنة، ونعزز استمرارية منصات البيانات الخاضعة للرقابة.',
                'service_type' => ServiceType::Development,
                'billing_type' => BillingType::Hourly,
                'pricing_type' => PricingType::Custom,
                'default_price' => 550,
                'is_featured' => false,
                'is_project_service' => true,
                'sort_order' => 3,
            ],
            [
                'code' => 'GLV-SLA',
                'category' => 'GO_LIVE_SUPPORT',
                'name' => 'Go-Live & SLA Support',
                'name_ar' => 'الإشراف على الإطلاق الحي والدعم الفني',
                'slug' => 'go-live-sla-support',
                'short_description' => 'Near-zero downtime banking cutover, first EOD hypercare, and contracted SLA maintenance.',
                'short_description_ar' => 'انتقال حي للأنظمة المصرفية بأقل توقف، دعم حرج لأول إغلاق يومي، وعقود صيانة وفق SLA.',
                'description' => 'Plan and execute production cutover for banking and financial systems: opening balances migration, first EOD supervision, on-site/remote hypercare, and ongoing SLA response with secure upgrades that protect operational stability.',
                'description_ar' => 'تخطيط وتنفيذ الانتقال للإنتاج للأنظمة المصرفية والمالية: نقل الأرصدة الافتتاحية، الإشراف على أول إغلاق يومي، دعم حرج ميداني وعن بُعد، وصيانة مستمرة وفق SLA مع ترقيات آمنة تحافظ على الاستقرار التشغيلي.',
                'overview' => 'We stay with bank and finance teams through go-live and beyond so the first critical closing and reconciliation cycles complete safely.',
                'overview_ar' => 'نرافق فرق البنوك والمالية خلال الإطلاق وما بعده لضمان سلامة دورات الإغلاق والمطابقة الحرجة الأولى.',
                'service_type' => ServiceType::Support,
                'billing_type' => BillingType::Recurring,
                'pricing_type' => PricingType::ContactUs,
                'default_price' => 15000,
                'is_featured' => true,
                'is_recurring' => true,
                'sort_order' => 4,
            ],
            [
                'code' => 'QA-SYS',
                'category' => 'QA_TESTING',
                'name' => 'QA & System Testing',
                'name_ar' => 'ضبط الجودة وفحص الأنظمة',
                'slug' => 'qa-system-testing',
                'short_description' => 'Financial UAT packs, stress/load testing, and security/integration audits before banking go-live.',
                'short_description_ar' => 'حزم قبول مالية واختبارات تحمل وفحص أمان وتكامل قبل الإطلاق المصرفي.',
                'description' => 'Independent quality assurance for financial and operational systems: acceptance test packs, edge cases, performance ceilings, data-flow integrity across interfaces, and vulnerability/authorization abuse simulations before production.',
                'description_ar' => 'ضمان جودة مستقل للأنظمة المالية والتشغيلية: حزم اختبار القبول، الحالات الحرجة، حدود الأداء، سلامة تدفق البيانات بين الواجهات، ومحاكاة الثغرات وانتحال الصلاحيات قبل الإنتاج.',
                'overview' => 'We validate banking and finance systems under realistic load so defects and bottlenecks are fixed before customers and regulators see them.',
                'overview_ar' => 'نتحقق من الأنظمة المصرفية والمالية تحت حمل واقعي لمعالجة العيوب والاختناقات قبل أن تظهر للعملاء أو الجهات الرقابية.',
                'service_type' => ServiceType::Consulting,
                'billing_type' => BillingType::Fixed,
                'pricing_type' => PricingType::Custom,
                'default_price' => 25000,
                'is_featured' => false,
                'is_consulting' => true,
                'sort_order' => 5,
            ],
            [
                'code' => 'DEV-FULL',
                'category' => 'SOFTWARE_DEV',
                'name' => 'Custom Software & Full-Stack Development',
                'name_ar' => 'تطوير وبرمجة الحلول المخصصة',
                'slug' => 'custom-fullstack-development',
                'short_description' => 'Custom web/mobile platforms and process automation for regulated financial environments.',
                'short_description_ar' => 'منصات ويب وجوال مخصصة وأتمتة عمليات للبيئات المالية المنظمة.',
                'description' => 'Full-stack delivery of enterprise portals and apps for banks and financial institutions: clean/microservices architecture, bilingual responsive UX, RBAC, secure backends, queues, encryption, and digital workflow automation.',
                'description_ar' => 'تسليم متكامل لبوابات وتطبيقات مؤسسية للبنوك والمؤسسات المالية: معماريات نظيفة/خدمات دقيقة، واجهات ثنائية اللغة، صلاحيات RBAC، أنظمة خلفية آمنة، طوابير، تشفير، وأتمتة مسارات العمل الرقمية.',
                'overview' => 'We engineer custom software that fits regulated, high-volume financial workflows—from channels and portals to async backends and automation.',
                'overview_ar' => 'نبني برمجيات مخصصة تناسب المسارات المالية المنظمة وعالية الحجم—من القنوات والبوابات إلى الأنظمة الخلفية غير المتزامنة والأتمتة.',
                'service_type' => ServiceType::Development,
                'billing_type' => BillingType::TimeAndMaterial,
                'pricing_type' => PricingType::QuoteRequired,
                'default_price' => 500,
                'is_featured' => false,
                'is_project_service' => true,
                'sort_order' => 6,
            ],
            [
                'code' => 'PRK-SMART',
                'category' => 'SMART_PARKING',
                'name' => 'Smart Parking Solutions',
                'name_ar' => 'تطوير وتشغيل أنظمة وتطبيقات المواقف الذكية',
                'slug' => 'smart-parking-solutions',
                'short_description' => 'Driver apps, parking management systems, ANPR/IoT hardware integration, and revenue analytics.',
                'short_description_ar' => 'تطبيقات السائقين ونظام إدارة المواقف والربط مع ANPR/IoT وتحليلات الإيرادات.',
                'description' => 'End-to-end smart parking: real-time availability and booking, dynamic pricing, VIP/staff permits, barrier and kiosk integration, ANPR/LPR, occupancy sensors, and financial/operational dashboards.',
                'description_ar' => 'حلول مواقف ذكية متكاملة: الشواغر والحجز لحظياً، تسعير ديناميكي، تصاريح VIP والموظفين، ربط البوابات والأكشاك، التعرف على اللوحات، حساسات الإشغال، ولوحات مالية وتشغيلية.',
                'overview' => 'We design, integrate, and operate parking platforms that maximize occupancy and revenue while reducing manual gate operations.',
                'overview_ar' => 'نصمم وندمج ونشغّل منصات مواقف تعظّم الإشغال والإيراد وتقلل العمليات اليدوية عند البوابات.',
                'service_type' => ServiceType::Development,
                'billing_type' => BillingType::Milestone,
                'pricing_type' => PricingType::QuoteRequired,
                'default_price' => 90000,
                'is_featured' => false,
                'is_project_service' => true,
                'sort_order' => 30,
            ],
            // Keep some internal-only ERP catalog items (not public)
            [
                'code' => 'PM-PLAN',
                'category' => 'PROJECT_MGMT',
                'name' => 'Project Planning & Governance',
                'name_ar' => 'تخطيط المشاريع والحوكمة',
                'slug' => 'project-planning-governance',
                'short_description' => 'Internal project planning service.',
                'short_description_ar' => 'خدمة تخطيط مشاريع داخلية.',
                'description' => 'Project planning and governance.',
                'description_ar' => 'تخطيط المشاريع والحوكمة.',
                'service_type' => ServiceType::Consulting,
                'billing_type' => BillingType::Hourly,
                'pricing_type' => PricingType::Fixed,
                'default_price' => 350,
                'is_consulting' => true,
                'is_public' => false,
                'sort_order' => 99,
            ],
        ];

        foreach ($services as $service) {
            $categoryId = ServiceCategory::query()->where('code', $service['category'])->value('id');
            if (! $categoryId) {
                continue;
            }

            $code = $service['code'];
            $isPublic = $service['is_public'] ?? true;
            unset($service['code'], $service['category'], $service['is_public']);

            Service::query()->updateOrCreate(
                ['service_code' => $code],
                array_merge([
                    'category_id' => $categoryId,
                    'short_name' => $service['name'],
                    'slug' => $service['slug'] ?? Str::slug($service['name']),
                    'unit' => 'hour',
                    'default_quantity' => 1,
                    'cost_price' => ($service['default_price'] ?? 0) * 0.6,
                    'currency_id' => $currencyId,
                    'tax_rate' => 15,
                    'is_consulting' => false,
                    'is_project_service' => false,
                    'is_recurring' => false,
                    'is_active' => true,
                    'is_public' => $isPublic,
                    'is_featured' => false,
                    'sort_order' => 0,
                    'starting_price' => null,
                    'meta_title' => $service['name'],
                    'meta_title_ar' => $service['name_ar'] ?? null,
                    'meta_description' => $service['short_description'] ?? null,
                    'meta_description_ar' => $service['short_description_ar'] ?? null,
                ], $service)
            );
        }
    }
}
